openapi: 3.0.0
info:
  title: Your API
  description: API documentation based on provided contract
  version: 1.0.0
paths:
  /login:
    post:
      summary: Authenticate user credentials and issue tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User authenticated successfully
        '400':
          description: Invalid email or password

  /generate-otp:
    get:
      summary: Generate OTP for password reset
      responses:
        '200':
          description: OTP generated successfully

  /reset-password:
    patch:
      summary: Reset user password using OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid OTP or email

  /refresh-auth:
    post:
      summary: Regenerate access token using refresh token
      responses:
        '200':
          description: Access token regenerated successfully

  /user/create-user:
    post:
      summary: Register a new user with cart and wishlist creation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User created successfully

  /product/get-product-parameters:
    get:
      summary: Fetch categories, colors, and sizes
      responses:
        '200':
          description: Product parameters fetched successfully

  /home:
    get:
      summary: Fetch banner and recent products
      responses:
        '200':
          description: Banner and recent products fetched successfully

  /list-products:
    get:
      summary: Fetch products based on various filters
      responses:
        '200':
          description: Products fetched successfully

  /product/{productId}:
    get:
      summary: Fetch details of a specific product
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details fetched successfully

  /user/wish-list:
    get:
      summary: Fetch user's wishlist
      responses:
        '200':
          description: User's wishlist fetched successfully

  /user/add-to-wishList:
    post:
      summary: Add product to wishlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
      responses:
        '200':
          description: Product added to wishlist successfully

  /user/remove-from-wishList:
    delete:
      summary: Remove product from wishlist
      responses:
        '200':
          description: Product removed from wishlist successfully

  /user/cart:
    get:
      summary: Fetch user's cart details
      responses:
        '200':
          description: User's cart details fetched successfully

  /user/cart/add-to-cart:
    post:
      summary: Add product to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Product added to cart successfully

  /user/cart/remove-from-cart:
    delete:
      summary: Remove product from cart
      responses:
        '200':
          description: Product removed from cart successfully

  /user/calculate-order-amount:
    get:
      summary: Calculate order amount based on products and shipping type
      responses:
        '200':
          description: Order amount calculated successfully

  /user/addresses:
    get:
      summary: Fetch user's addresses
      responses:
        '200':
          description: User's addresses fetched successfully

  /user/add-address:
    post:
      summary: Add user address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        '200':
          description: User address added successfully

  /user/create-order:
    post:
      summary: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                shippingType:
                  type: string
      responses:
        '200':
          description: Order created successfully

  /user/verify-payment:
    post:
      summary: Verify payment signature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentSignature:
                  type: string
      responses:
        '200':
          description: Payment verified successfully

  /user/view-orders:
    get:
      summary: Fetch user's orders
      responses:
        '200':
          description: User's orders fetched successfully

  /product/reviews:
    get:
      summary: Fetch reviews of a product
      responses:
        '200':
          description: Product reviews fetched successfully

  /user/create-review:
    post:
      summary: Add a review for a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                rating:
                  type: integer
                comment:
                  type: string
      responses:
        '200':
          description: Review added successfully

  /admin/add-product:
    post:
      summary: Add a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                category:
                  type: string
                color:
                  type: string
                size:
                  type: string
      responses:
        '200':
          description: Product added successfully

  /admin/edit-product:
    put:
      summary: Update product details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                name:
                  type: string
                description:
                  type: string
                price:
                  type: number
                category:
                  type: string
                color:
                  type: string
                size:
                  type: string
      responses:
        '200':
          description: Product updated successfully

  /admin/delete-product:
    delete:
      summary: Delete a product
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully

  /admin/view-orders:
    get:
      summary: Fetch all orders (admin)
      responses:
        '200':
          description: Orders fetched successfully

  /admin/view-order:
    get:
      summary: Fetch details of a specific order (admin)
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details fetched successfully

  /admin/order-status:
    get:
      summary: Fetch status of a specific order (admin)
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order status fetched successfully

  /admin/update-order:
    patch:
      summary: Update order details (admin)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Order updated successfully
